name: Test and Lint

on:
    push:
        branches: [main]
    pull_request:
        branches:
            - "*"

jobs:
    lint:
        name: Lint Code
        runs-on: ubuntu-latest
        steps:
            - name: Repository checkout
              uses: actions/checkout@v5
            - name: Get swift version
              run: swift --version
            - name: Lint
              run: make checklint
    test:
        name: Test ${{ matrix.xcodebuildCommand }}
        runs-on: "macos-26"
        strategy:
            fail-fast: true
            matrix:
                xcodebuildCommand:
                    - "-sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 17'"
                    - "-sdk macosx -destination 'platform=macOS'"
                    - "-sdk xrsimulator -destination 'platform=visionOS Simulator,name=Apple Vision Pro'"
                    - "-sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation)'"
                    - "-sdk watchsimulator -destination 'platform=watchOS Simulator,name=Apple Watch Series 11 (46mm)'"
        steps:
            - name: Repository checkout
              uses: actions/checkout@v6
            - name: Select Xcode version
              run: sudo xcode-select -s '/Applications/Xcode_26.4.1.app/Contents/Developer'
            - name: Build and Test
              run: xcodebuild test -scheme TelemetryDeck-Package ${{ matrix.xcodebuildCommand }}
